"""Compute reverse-direction transfer summary + figure, and emit LaTeX macros.

Reads:
  results_v6/transfer/transfer_cv.json             (forward Por->Math)
  results_v6/transfer/transfer_cv_reverse.json     (reverse Math->Por)

Writes:
  submission_package/vtse_submission_20260601/figures/reverse_transfer.png
  submission_package/vtse_submission_20260601/_reverse_macros.tex
"""
from __future__ import annotations

import json
import pathlib

import matplotlib.pyplot as plt
import numpy as np

RESULTS = pathlib.Path("results_v6")
SUB = pathlib.Path("submission_package/vtse_submission_20260601")


def mean_method(d, m):
    return float(np.mean(d["_fold_rmse"][m]))


def main():
    fwd = json.load(open(RESULTS / "transfer" / "transfer_cv.json"))
    rev = json.load(open(RESULTS / "transfer" / "transfer_cv_reverse.json"))

    methods = ["target_only", "pooled", "warm_start", "tradaboost_r2",
               "coral", "gated"]
    fwd_means = {m: mean_method(fwd, m) for m in methods}
    rev_means = {m: mean_method(rev, m) for m in methods}

    rev_gate_decisions = rev.get("gate_decisions", [])
    n_chose = sum(1 for g in rev_gate_decisions if g.get("chose_transfer"))
    n_total = len(rev_gate_decisions)
    rev_gated_delta = rev_means["gated"] - rev_means["target_only"]
    fwd_gated_delta = fwd_means["gated"] - fwd_means["target_only"]

    print(f"Forward Por->Math: target_only={fwd_means['target_only']:.3f}, "
          f"gated={fwd_means['gated']:.3f}, delta={fwd_gated_delta:+.3f}")
    print(f"Reverse Math->Por: target_only={rev_means['target_only']:.3f}, "
          f"gated={rev_means['gated']:.3f}, delta={rev_gated_delta:+.3f}")
    print(f"Reverse gate fallback: {n_total - n_chose}/{n_total}")

    # Emit LaTeX macros file
    macros = f"""% Auto-generated by src/compute_reverse_transfer.py
\\renewcommand{{\\reverseTargetOnly}}{{${rev_means['target_only']:.3f}$}}
\\renewcommand{{\\reversePooled}}{{${rev_means['pooled']:.3f}$}}
\\renewcommand{{\\reverseWarmStart}}{{${rev_means['warm_start']:.3f}$}}
\\renewcommand{{\\reverseGated}}{{${rev_means['gated']:.3f}$}}
\\renewcommand{{\\reverseGatedDelta}}{{${rev_gated_delta:+.3f}$}}
\\renewcommand{{\\reverseGateRate}}{{${n_total - n_chose}/{n_total}$}}
"""
    out_tex = SUB / "_reverse_macros.tex"
    out_tex.write_text(macros, encoding="utf-8")
    print(f"wrote {out_tex}")

    # Figure: side-by-side bars
    plot_methods = ["target_only", "pooled", "warm_start", "gated"]
    labels = ["Target-only", "Pooled", "Warm-start", "Gated"]
    fwd_vals = [fwd_means[m] for m in plot_methods]
    rev_vals = [rev_means[m] for m in plot_methods]

    x = np.arange(len(plot_methods))
    width = 0.36
    fig, ax = plt.subplots(figsize=(7.2, 4.4))
    b1 = ax.bar(x - width/2, fwd_vals, width,
                label="Por$\\rightarrow$Math (target $n=395$)",
                color="#2E86AB", edgecolor="black", linewidth=0.7)
    b2 = ax.bar(x + width/2, rev_vals, width,
                label="Math$\\rightarrow$Por (target $n=649$)",
                color="#E94F37", edgecolor="black", linewidth=0.7)
    for bars in [b1, b2]:
        for b in bars:
            h = b.get_height()
            ax.text(b.get_x() + b.get_width() / 2, h + 0.02,
                    f"{h:.2f}", ha="center", va="bottom", fontsize=8)
    ax.set_xticks(x)
    ax.set_xticklabels(labels, fontsize=10)
    ax.set_ylabel("Mean RMSE (50 folds)")
    ax.set_title("Forward vs.\\ reverse transfer direction (mean RMSE per method)",
                 fontsize=11)
    ax.legend(loc="upper left", fontsize=9, frameon=True)
    ax.grid(axis="y", linestyle=":", alpha=0.5)
    ymin = min(min(fwd_vals), min(rev_vals)) * 0.9
    ymax = max(max(fwd_vals), max(rev_vals)) * 1.08
    ax.set_ylim(ymin, ymax)
    fig.tight_layout()
    out_png = SUB / "figures" / "reverse_transfer.png"
    fig.savefig(out_png, dpi=180, bbox_inches="tight")
    plt.close(fig)
    print(f"wrote {out_png}")


if __name__ == "__main__":
    main()
